// Auto-generated model.glsl
#include "pass_conv2d_tf.glsl"
#include "pass_conv2d_1_tf.glsl"
#include "pass_conv2d_2_tf.glsl"
#include "pass_conv2d_3_tf.glsl"
#include "pass_conv2d_4_tf.glsl"
#include "pass_conv2d_5_tf.glsl"
#include "pass_conv2d_6_tf.glsl"
#include "pass_conv2d_7_tf.glsl"
#include "pass_conv2d_7_tf1.glsl"
#include "pass_conv2d_7_tf2.glsl"
#include "pass_depth_to_space2_tf.glsl"
#include "pass_up_sampling2d_tf.glsl"
#include "pass_add_tf.glsl"
