#common
java_version=17
minecraft_version=1.20.1
parchment_version=1.20.1:2023.09.03
platforms=fabric,forge
lwjgl_version=3.3.1
architectury_api_version=9.1.12
forgelike_mod_minecraft_version_range=[1.20.1,)
fabriclike_mod_minecraft_version_range=~1.20.1
cloth_config_version=11.1.136
mod_artifact_minecraft_ver=1.20.1
#fabric
fabric_loader_version=0.15.11
fabric_api_version=0.92.2+1.20.1
fabric_use_modrinth_mods=reeses-sodium-options,xaeros-world-map,xaeros-minimap,distanthorizons,iris,sodium,indium
fabric_use_modrinth_mod_ver_reeses-sodium-options=mc1.20.1-1.7.2
fabric_use_modrinth_mod_ver_xaeros-world-map=1.39.2_Fabric_1.20
fabric_use_modrinth_mod_ver_xaeros-minimap=25.1.0_Fabric_1.20
fabric_use_modrinth_mod_ver_distanthorizons=2.2.1-a-1.20.1
fabric_use_modrinth_mod_ver_iris=1.7.5+1.20.1
fabric_use_modrinth_mod_ver_sodium=mc1.20.1-0.5.11
fabric_use_modrinth_mod_ver_indium=1.0.34+mc1.20.1
modmenu_version=7.2.2
#forge
forge_version=47.3.1
forge_use_modrinth_mods=xaeros-world-map,xaeros-minimap,timeless-and-classics-zero,embeddium,oculus,simple-clouds
forge_use_modrinth_mod_ver_xaeros-world-map=1.39.2_Forge_1.20
forge_use_modrinth_mod_ver_xaeros-minimap=25.1.0_Forge_1.20
forge_use_modrinth_mod_ver_timeless-and-classics-zero=1.1.4-hotfix
forge_use_modrinth_mod_ver_embeddium=0.3.31+mc1.20.1
forge_use_modrinth_mod_ver_oculus=1.20.1-1.8.0
forge_use_modrinth_mod_ver_simple-clouds=0.6.3+1.20.1-forge
forge_use_mod_lib=crackerslib-forge-1.20.1-0.4.4
forge_use_nomod_lib=luaj-jse-3.0.8-figura,luaj-core-3.0.8-figura