#common
java_version=21
minecraft_version=1.21.1
parchment_version=1.21.1:2024.11.17
platforms=fabric,neoforge
lwjgl_version=3.3.3
architectury_api_version=13.0.6
forgelike_mod_minecraft_version_range=[1.20.1,)
fabriclike_mod_minecraft_version_range=~1.21.1,~1.21
mod_artifact_minecraft_ver=1.21~1.21.1
#fabric
fabric_loader_version=0.16.7
fabric_api_version=0.105.0+1.21.1
fabric_use_modrinth_mods=reeses-sodium-options,xaeros-world-map,xaeros-minimap
fabric_use_modrinth_mod_ver_reeses-sodium-options=mc1.21.4-1.8.3+fabric
fabric_use_modrinth_mod_ver_xaeros-world-map=1.39.2_Fabric_1.21
fabric_use_modrinth_mod_ver_xaeros-minimap=25.1.0_Fabric_1.21
modmenu_version=11.0.1
#neoforge
neoforge_version=21.1.89
neoforge_use_modrinth_mods=reeses-sodium-options,xaeros-world-map,xaeros-minimap,spark
neoforge_use_modrinth_mod_ver_reeses-sodium-options=mc1.21.4-1.8.3+neoforge
neoforge_use_modrinth_mod_ver_xaeros-world-map=1.39.2_NeoForge_1.21
neoforge_use_modrinth_mod_ver_xaeros-minimap=25.1.0_NeoForge_1.21
neoforge_use_modrinth_mod_ver_spark=1.10.109-neoforge