#common
java_version=21
minecraft_version=1.21.4
parchment_version=1.21.4:2025.02.16
platforms=fabric,neoforge
lwjgl_version=3.3.3
architectury_api_version=15.0.3
forgelike_mod_minecraft_version_range=[1.21.4,)
fabriclike_mod_minecraft_version_range=~1.21.4
cloth_config_version=17.0.144
mod_artifact_minecraft_ver=1.21.4
#fabric
fabric_loader_version=0.16.10
fabric_api_version=0.118.0+1.21.4
fabric_use_modrinth_mods=reeses-sodium-options,iris,sodium
fabric_use_modrinth_mod_ver_reeses-sodium-options=mc1.21.4-1.8.3+fabric
fabric_use_modrinth_mod_ver_iris=1.8.8+1.21.4-fabric
fabric_use_modrinth_mod_ver_sodium=mc1.21.4-0.6.10-fabric
modmenu_version=11.0.1
#neoforge
neoforge_version=21.4.109-beta
neoforge_use_modrinth_mods=reeses-sodium-options,sodium,iris
neoforge_use_modrinth_mod_ver_reeses-sodium-options=mc1.21.4-1.8.3+neoforge
neoforge_use_modrinth_mod_ver_sodium=mc1.21.4-0.6.10-neoforge
neoforge_use_modrinth_mod_ver_iris=1.8.8+1.21.4-neoforge
neoforge_use_mod_lib=fabric-api-base-0.4.42+d1308ded19,fabric-block-view-api-v2-1.0.10+9afaaf8c19,fabric-renderer-api-v1-5.0.0+babc52e504,fabric-rendering-data-attachment-v1-0.3.48+73761d2e19,net.caffeinemc.sodium-neoforge-0.6.10+mc1.21.4-service
neoforge_use_nomod_lib=jcpp-1.4.14,glsl-transformer-2.0.1,antlr4-runtime-4.13.1
