#common
java_version=21
minecraft_version=1.21.1
parchment_version=1.21.1:2024.11.17
platforms=fabric,neoforge
lwjgl_version=3.3.3
architectury_api_version=13.0.6
forgelike_mod_minecraft_version_range=[1.21.1,)
fabriclike_mod_minecraft_version_range=~1.21.1,~1.21
cloth_config_version=15.0.140
mod_artifact_minecraft_ver=1.21~1.21.1
#fabric
fabric_loader_version=0.16.7
fabric_api_version=0.105.0+1.21.1
fabric_use_modrinth_mods=reeses-sodium-options,xaeros-world-map,xaeros-minimap,iris,sodium,distanthorizons,spark
fabric_use_modrinth_mod_ver_reeses-sodium-options=mc1.21.4-1.8.3+fabric
fabric_use_modrinth_mod_ver_xaeros-world-map=1.39.2_Fabric_1.21
fabric_use_modrinth_mod_ver_xaeros-minimap=25.1.0_Fabric_1.21
fabric_use_modrinth_mod_ver_iris=1.8.1+1.21.1-fabric
fabric_use_modrinth_mod_ver_sodium=mc1.21.1-0.6.5-fabric
fabric_use_modrinth_mod_ver_distanthorizons=2.2.1-a-1.21.1
fabric_use_modrinth_mod_ver_spark=1.10.109-fabric
fabric_use_mod_lib=fabric-permissions-api-0.3.1
modmenu_version=11.0.1
#neoforge
neoforge_version=21.1.89
neoforge_use_modrinth_mods=reeses-sodium-options,xaeros-world-map,xaeros-minimap,spark,sodium,distanthorizons,iris
neoforge_use_modrinth_mod_ver_reeses-sodium-options=mc1.21.4-1.8.3+neoforge
neoforge_use_modrinth_mod_ver_xaeros-world-map=1.39.2_NeoForge_1.21
neoforge_use_modrinth_mod_ver_xaeros-minimap=25.1.0_NeoForge_1.21
neoforge_use_modrinth_mod_ver_spark=1.10.109-neoforge
neoforge_use_modrinth_mod_ver_sodium=mc1.21.1-0.6.7-neoforge
neoforge_use_modrinth_mod_ver_distanthorizons=2.2.1-a-1.21.1
neoforge_use_modrinth_mod_ver_iris=1.8.1+1.21.1-neoforge
neoforge_use_mod_lib=fabric-api-base-0.4.42+d1308ded19,fabric-block-view-api-v2-1.0.10+9afaaf8c19,fabric-renderer-api-v1-3.4.0+acb05a3919,fabric-rendering-data-attachment-v1-0.3.48+73761d2e19,net.caffeinemc.sodium-neoforge-0.6.5+mc1.21.1-service