/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_homo_superresolution_core_SuperResolutionNative */

#ifndef _Included_io_homo_superresolution_core_SuperResolutionNative
#define _Included_io_homo_superresolution_core_SuperResolutionNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    getVersionInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_getVersionInfo
  (JNIEnv *, jclass);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    compileShaderToSpirv
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIIIIIIZZ)Lio/homo/superresolution/core/glslang/GlslangCompileShaderResult;
 */
JNIEXPORT jobject JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_compileShaderToSpirv
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    initGlslang
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_initGlslang
  (JNIEnv *, jclass);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    destroyGlslang
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_destroyGlslang
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
