/* DO NOT EDIT THIS FILE - it is machine generated - 才怪*/
#ifdef ON_LINUX
#include "jni_linux64.h"
#else
#include "jni.h"
#endif
/* Header for class oiiaio_fsr_fsr2_FfxFSR2 */

#ifndef _Included_oiiaio_fsr_fsr2_FfxFSR2
#define _Included_oiiaio_fsr_fsr2_FfxFSR2
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxFsr2ContextDestroy
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxFsr2ContextDestroy(JNIEnv *, jobject, jlong);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxFsr2ContextDispatch
   * Signature: (Loiiaio/fsr/fsr2/impl/FfxResource;Loiiaio/fsr/fsr2/impl/FfxResource;Loiiaio/fsr/fsr2/impl/FfxResource;Loiiaio/fsr/fsr2/impl/FfxResource;Loiiaio/fsr/fsr2/impl/FfxResource;Loiiaio/fsr/fsr2/impl/FfxResource;Loiiaio/fsr/fsr2/impl/FfxResource;FFFFIIZFFFZFFFFZJ)I
   */
  JNIEXPORT jint JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxFsr2ContextDispatch(JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jfloat, jfloat, jfloat, jfloat, jint, jint, jboolean, jfloat, jfloat, jfloat, jboolean, jfloat, jfloat, jfloat, jfloat, jboolean, jlong);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxFsr2CreateGL
   * Signature: (IFIII)[J
   */
  JNIEXPORT jlongArray JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxFsr2CreateGL(JNIEnv *, jobject, jint, jfloat, jint, jint, jint);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxGetTextureResourceVk
   * Signature: (JJIII)Loiiaio/fsr/fsr2/impl/FfxResource;
   */
  JNIEXPORT jobject JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxGetTextureResourceVk(JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxFsr2CreateVk
   * Signature: (JJIFIII)[I
   */
  JNIEXPORT jintArray JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxFsr2CreateVk(JNIEnv *, jobject, jlong, jlong, jint, jfloat, jint, jint, jint);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxFsr2GetScratchMemorySizeVk
   * Signature: (J)I
   */
  JNIEXPORT jint JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxFsr2GetScratchMemorySizeVk(JNIEnv *, jobject, jlong);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxGetCommandListVK
   * Signature: (J)J
   */
  JNIEXPORT jlong JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxGetCommandListVK(JNIEnv *, jobject, jlong);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    getVersionInfo
   * Signature: ()Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_getVersionInfo(JNIEnv *, jobject);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxFsr2GetJitterPhaseCount
   * Signature: (II)I
   */
  JNIEXPORT jint JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxFsr2GetJitterPhaseCount(JNIEnv *, jobject, jint, jint);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxFsr2GetJitterOffset
   * Signature: (II)[F
   */
  JNIEXPORT jfloatArray JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxFsr2GetJitterOffset(JNIEnv *, jobject, jint, jint);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxGetTextureResourceGL
   * Signature: (JIII)Loiiaio/fsr/fsr2/impl/FfxResource;
   */
  JNIEXPORT jobject JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxGetTextureResourceGL(JNIEnv *, jobject, jlong, jint, jint, jint);

  /*
   * Class:     oiiaio_fsr_fsr2_FfxFSR2
   * Method:    ffxFsr2GetScratchMemorySizeGL
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL Java_oiiaio_fsr_fsr2_FfxFSR2_ffxFsr2GetScratchMemorySizeGL(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
