modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "super_resolution_xess"
version = "${version}"
displayName = "Super Resolution"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.super_resolution_xess]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.super_resolution_xess]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


