package io.homo.superresolution.fsr2.types.enums;

public enum FfxSurfaceFormat {
    FFX_SURFACE_FORMAT_UNKNOWN(0),
    FFX_SURFACE_FORMAT_R32G32B32A32_TYPELESS(1),
    FFX_SURFACE_FORMAT_R32G32B32A32_FLOAT(2),
    FFX_SURFACE_FORMAT_R16G16B16A16_FLOAT(3),
    FFX_SURFACE_FORMAT_R16G16B16A16_UNORM(4),
    FFX_SURFACE_FORMAT_R32G32_FLOAT(5),
    FFX_SURFACE_FORMAT_R32_UINT(6),
    FFX_SURFACE_FORMAT_R8G8B8A8_TYPELESS(7),
    FFX_SURFACE_FORMAT_R8G8B8A8_UNORM(8),
    FFX_SURFACE_FORMAT_R11G11B10_FLOAT(9),
    FFX_SURFACE_FORMAT_R16G16_FLOAT(10),
    FFX_SURFACE_FORMAT_R16G16_UINT(11),
    FFX_SURFACE_FORMAT_R16_FLOAT(12),
    FFX_SURFACE_FORMAT_R16_UINT(13),
    FFX_SURFACE_FORMAT_R16_UNORM(14),
    FFX_SURFACE_FORMAT_R16_SNORM(15),
    FFX_SURFACE_FORMAT_R8_UNORM(16),
    FFX_SURFACE_FORMAT_R8_UINT(17),
    FFX_SURFACE_FORMAT_R8G8_UNORM(18),
    FFX_SURFACE_FORMAT_R32_FLOAT(19);

    private final int value;

    FfxSurfaceFormat(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
