/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni/jni.h"
/* Header for class io_homo_superresolution_thirdparty_nanovg_NanoVGPaint */

#ifndef _Included_io_homo_superresolution_thirdparty_nanovg_NanoVGPaint
#define _Included_io_homo_superresolution_thirdparty_nanovg_NanoVGPaint
#ifdef __cplusplus
extern "C" {
    #endif
    /*
 * Class:     io_homo_superresolution_thirdparty_nanovg_NanoVGPaint
 * Method:    nDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_homo_superresolution_thirdparty_nanovg_NanoVGPaint_nDelete
    (JNIEnv *, jobject, jlong);

    #ifdef __cplusplus
}
#endif
#endif