/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni/jni.h"
/* Header for class io_homo_superresolution_thirdparty_nanovg_NanoVGColor */

#ifndef _Included_io_homo_superresolution_thirdparty_nanovg_NanoVGColor
#define _Included_io_homo_superresolution_thirdparty_nanovg_NanoVGColor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_homo_superresolution_thirdparty_nanovg_NanoVGColor
 * Method:    nGetNanoVGColorR
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_io_homo_superresolution_thirdparty_nanovg_NanoVGColor_nGetNanoVGColorR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_homo_superresolution_thirdparty_nanovg_NanoVGColor
 * Method:    nGetNanoVGColorG
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_io_homo_superresolution_thirdparty_nanovg_NanoVGColor_nGetNanoVGColorG
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_homo_superresolution_thirdparty_nanovg_NanoVGColor
 * Method:    nGetNanoVGColorB
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_io_homo_superresolution_thirdparty_nanovg_NanoVGColor_nGetNanoVGColorB
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_homo_superresolution_thirdparty_nanovg_NanoVGColor
 * Method:    nGetNanoVGColorA
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_io_homo_superresolution_thirdparty_nanovg_NanoVGColor_nGetNanoVGColorA
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_homo_superresolution_thirdparty_nanovg_NanoVGColor
 * Method:    nDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_homo_superresolution_thirdparty_nanovg_NanoVGColor_nDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
