/* DO NOT EDIT THIS FILE - it is machine generated */
#include "JNI0.h"
/* Header for class io_homo_superresolution_core_SuperResolutionNative */

#ifndef _Included_io_homo_superresolution_core_SuperResolutionNative
#define _Included_io_homo_superresolution_core_SuperResolutionNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    getVersionInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_getVersionInfo
  (JNIEnv *, jclass);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    compileShaderToSpirv
 * Signature: (Ljava/lang/String;IIIIIIIIZZ)Lio/homo/superresolution/core/graphics/glslang/GlslangCompileShaderResult;
 */
JNIEXPORT jobject JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_compileShaderToSpirv
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    freeDirectBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_freeDirectBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    initGlslang
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_initGlslang
  (JNIEnv *, jclass);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    destroyGlslang
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_destroyGlslang
  (JNIEnv *, jclass);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    NsrCreateUpscaleContext
 * Signature: (Lio/homo/superresolution/srapi/SRUpscaleContext;JJJIIIII)I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_NsrCreateUpscaleContext
  (JNIEnv *, jclass, jobject, jlong, jlong, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    NsrDestroyUpscaleContext
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_NsrDestroyUpscaleContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    NsrDispatchUpscale
 * Signature: (JJLio/homo/superresolution/srapi/SRTextureResource;Lio/homo/superresolution/srapi/SRTextureResource;Lio/homo/superresolution/srapi/SRTextureResource;Lio/homo/superresolution/srapi/SRTextureResource;Lio/homo/superresolution/srapi/SRTextureResource;Lio/homo/superresolution/srapi/SRTextureResource;Lio/homo/superresolution/srapi/SRTextureResource;FFFFIIIIFZFFFFFFZI)I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_NsrDispatchUpscale
  (JNIEnv *, jclass, jlong, jlong, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jfloat, jboolean, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean, jint);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    NsrQueryUpscaleContext
 * Signature: (JLio/homo/superresolution/srapi/SRUpscaleContextQueryResult;I)I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_NsrQueryUpscaleContext
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    NsrGetUpscaleProvider
 * Signature: (Lio/homo/superresolution/srapi/SRUpscaleProvider;J)I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_NsrGetUpscaleProvider
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     io_homo_superresolution_core_SuperResolutionNative
 * Method:    NsrLoadUpscaleProvidersFromLibrary
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_SuperResolutionNative_NsrLoadUpscaleProvidersFromLibrary
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
