/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api */

#ifndef _Included_io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
#define _Included_io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_init
  (JNIEnv *, jobject);

/*
 * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
 * Method:    ffxFsr2GetScratchMemorySizeGL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2GetScratchMemorySizeGL
  (JNIEnv *, jobject);

/*
 * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
 * Method:    ffxFsr2CreateContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2CreateContext
  (JNIEnv *, jobject);

/*
 * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
 * Method:    ffxFsr2GetInterfaceGL
 * Signature: (IFIII)I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2GetInterfaceGL
  (JNIEnv *, jobject, jint, jfloat, jint, jint, jint);

/*
 * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
 * Method:    ffxFsr2Test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2Test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
